kind: pipeline
type: docker
name: build

steps:
  - name: docker-${DRONE_BRANCH}
    image: plugins/docker:18.09
    settings:
      registry: registry.cn-hangzhou.aliyuncs.com
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      insecure: true
      tags: latest
      dockerfile: Dockerfile
      repo: registry.cn-hangzhou.aliyuncs.com/aliyun-service/gotest
  - name: ssh commands
    image: appleboy/drone-ssh
    settings:
      host: 192.168.205.10
      username: root
      password: 123456789
      port: 22
      script:
        - echo ====暂停容器开始=======
        - docker stop `docker ps -a | grep gotest | awk '{print $1}' `
        - docker rm -f `docker ps -a | grep gotest | awk '{print $1}' `
        - docker rmi -f `docker images | grep gotest | awk '{print $1}' `
        - echo ====开始部署=======
        - docker pull registry.cn-hangzhou.aliyuncs.com/aliyun-service/gotest
        - docker run -d --name=gotest registry.cn-hangzhou.aliyuncs.com/aliyun-service/gotest
        - echo ====部署成功======

trigger:
  branch:
    - master
  event:
    - push